---
language: minimal
sudo: required
dist: xenial

addons:
  apt:
    packages:
      # https://github.com/puppeteer/puppeteer/blob/main/docs/troubleshooting.md#chrome-headless-doesnt-launch-on-unix
      - libatk-bridge2.0-0
      - libgtk-3-0
  chrome: stable
  firefox: latest

cache:
  directories:
    - /home/travis/.volta/
    - /home/travis/.yarn/

env:
  global:
    # See https://git.io/vdao3 for details.
    - JOBS=1

branches:
  only:
    - master
    # npm version tags
    - /^v\d+\.\d+\.\d+/

jobs:
  fast_finish: true
  allow_failures:
    - env: EMBER_TRY_SCENARIO=ember-beta
    - env: EMBER_TRY_SCENARIO=ember-canary

  include:
    # runs linting and tests with current locked deps

    - stage: "Tests"
      name: "Tests"
      script:
        - yarn lint:hbs
        - yarn lint:js
        - yarn test

    # we recommend new addons test the current and previous LTS
    # as well as latest stable release (bonus points to beta/canary)
    - stage: "Additional Tests"
      env: EMBER_TRY_SCENARIO=ember-lts-2.4
    - env: EMBER_TRY_SCENARIO=ember-lts-2.8
    - env: EMBER_TRY_SCENARIO=ember-lts-2.12
    - env: EMBER_TRY_SCENARIO=ember-lts-2.16
    - env: EMBER_TRY_SCENARIO=ember-lts-2.18
    - env: EMBER_TRY_SCENARIO=ember-lts-3.4
    - env: EMBER_TRY_SCENARIO=ember-lts-3.8
    - env: EMBER_TRY_SCENARIO=ember-lts-3.12
    - env: EMBER_TRY_SCENARIO=ember-lts-3.16
    - env: EMBER_TRY_SCENARIO=ember-release
    - env: EMBER_TRY_SCENARIO=ember-beta
    - env: EMBER_TRY_SCENARIO=ember-canary
    - env: EMBER_TRY_SCENARIO=ember-default-with-jquery
    - env: EMBER_TRY_SCENARIO=embroider-tests
    - env: EMBER_TRY_SCENARIO=typescript-3.7
      before_script: find tests/types -type f -name '*.ts' | xargs sed -i 's/@ts-expect-error/@ts-ignore/g'
    - env: EMBER_TRY_SCENARIO=typescript-3.9
    - env: EMBER_TRY_SCENARIO=ember-default
      before_install: rm package.json && mv package.node-8.json package.json

install:
  - curl https://get.volta.sh | bash
  - export VOLTA_HOME="/home/travis/.volta"
  - export PATH="$VOLTA_HOME/bin:$PATH"
  - yarn install --non-interactive

script:
  - yarn ember try:one $EMBER_TRY_SCENARIO
